return {
	"neovim/nvim-lspconfig",
	enabled = false,
	config = function()
		local capabilities = vim.lsp.protocol.make_client_capabilities()
		capabilities.offsetEncoding = { "utf-16" }

		local servers = {
			"tinymist",
			"pylsp",
			"html",
			"cssls",
			"lua_ls",
			"emmet_ls",
			"bashls",
			"ts_ls",
			-- "ccls",
			"clangd",
			"jdtls",
			"taplo",
			"gopls",
			"solidity",
			"zls",
			"marksman",
			-- "crystalline",
			"kotlin_language_server",
			-- "wgsl_analyzer",
			-- "hls",
			"jsonls",
			"svelte",
			-- "solidity_ls",
		}
	end,
	lazy = true,
	cmd = { "LspInfo", "LspLog", "LspRestart", "LspStart", "LspStop" },
	ft = {
		"rust",
		"lua",
		"python",
		"c",
		"cpp",
		"c++",
		"javascript",
		"java",
		"typescript",
		"toml",
		"php",
		"bash",
		"kdl",
		"fish",
		"go",
		"c#",
		"vb",
		"cs",
		"json",
		"jsonc",
		"typst",
		"html",
		"svelte",
	},
}
