return {
	"neovim/nvim-lspconfig",
	enabled = false,
	config = function()
		local capabilities = vim.lsp.protocol.make_client_capabilities()
		capabilities.offsetEncoding = { "utf-16" }
	end,
	lazy = true,
	cmd = { "LspInfo", "LspLog", "LspRestart", "LspStart", "LspStop" },
	ft = {
		"rust",
		"lua",
		"python",
		"c",
		"cpp",
		"c++",
		"javascript",
		"java",
		"typescript",
		"toml",
		"php",
		"bash",
		"kdl",
		"fish",
		"go",
		"c#",
		"vb",
		"cs",
		"json",
		"jsonc",
		"typst",
		"html",
		"svelte",
	},
}
